
obj-$(CONFIG_EDM) += edm.o edm_display.o
obj-$(CONFIG_EDM_BASEBOARD_WAND) += baseboard-wand.o
obj-$(CONFIG_EDM_BASEBOARD_FAIRY) += baseboard-fairy.o
obj-$(CONFIG_EDM_EXPANSION_FWBADAPT) += expansion-fwbadapt.o
obj-$(CONFIG_EDM_EXPANSION_WANDQC) += expansion-wandqc.o
